# Generated by Django 5.1.15 on 2026-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_state_codes_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsetting',
            name='dark_mode_default',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='login_bg',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='primary_color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='secondary_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='system_name',
            field=models.CharField(default='Vardhan ERP', max_length=255),
        ),
    ]
