# Generated by Django 5.1.15 on 2026-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsetting',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='login_bg',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
