# Generated by Django 5.1.15 on 2026-04-20 15:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_no', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('logo_base64', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_profiles',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('gst_einvoice', 'GST E-Invoice'), ('challan', 'Challan Cum Invoice'), ('gst_logo', 'GST Invoice with Logo')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField(blank=True, default='')),
                ('buyer_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('buyer_state', models.CharField(blank=True, default='', max_length=100)),
                ('buyer_state_code', models.CharField(blank=True, default='', max_length=2)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_order_no', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_note_no', models.CharField(blank=True, default='', max_length=50)),
                ('irn', models.CharField(blank=True, default='', max_length=100)),
                ('ack_no', models.CharField(blank=True, default='', max_length=50)),
                ('ack_date', models.DateField(blank=True, null=True)),
                ('line_items', models.JSONField(default=list)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
