# Generated by Django 5.1.15 on 2026-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='challan_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
